version: "3.9"

volumes:
  pgdata: { }

services:
  postgres:
    container_name: 'postgres'
    image: postgres:14.0
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: '.env'

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  migrations:
    container_name: 'migrations'
    image: upravbal/my_simplaner:version-1

    volumes:
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  api:
    container_name: 'api'
    image: upravbal/my_simplaner:version-1
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - migrations


  front:
    container_name: 'frontend'
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 80:80
    depends_on:
      - api




