# Generated by Django 4.0.1 on 2023-03-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_remove_goal_user_alter_goal_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalComment',
        ),
    ]
